server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: /Users/genil/src/microservices/cloud/thoughtmechanix/config-server-repo
#Disable security of the management endpoint
management:
  security:
    enabled: false
